<?php

class dberror
{
    const NO_MYSQLI_EXCEPTION = "MYSQLI EXCEPTION";
    const NO_MYSQL_EXCEPTION = "MYSQL EXCEPTION";
    const SQL_EXCEPTION = "SQL EXCEPTION";
    const CONNECT_EXCEPTION = "CONNECT EXCEPTION";
    const MYSQL_NO_PREPARE_EXCEPTION = "MYSQL NO PREPARE EXCEPTION";
}